-- AlterTable
ALTER TABLE "landing_settings" DROP COLUMN "blogEyebrow",
DROP COLUMN "blogPosts",
DROP COLUMN "blogTitle",
DROP COLUMN "contactEmail",
DROP COLUMN "contactPhone",
DROP COLUMN "features",
DROP COLUMN "featuresEyebrow",
DROP COLUMN "featuresTitle",
DROP COLUMN "heroDemoVideoUrl",
DROP COLUMN "heroTitle",
DROP COLUMN "paymentsEyebrow",
DROP COLUMN "paymentsTitle",
DROP COLUMN "roles",
DROP COLUMN "rolesEyebrow",
DROP COLUMN "rolesTitle",
DROP COLUMN "socialFacebookUrl",
DROP COLUMN "socialInstagramUrl",
DROP COLUMN "socialLinkedinUrl",
DROP COLUMN "socialTwitterUrl";
